### ISSUE TITLE
Error - running test run. 

### ISSUE THREAD

**Issue by vinsilico** [QuKunLab/SpatialBenchmarking#15]
I am getting this error while I was testing my installation with dataset15. It fails in the novoSpaRc methods.Any advice will be much appreciated. Thanks

Traceback (most recent call last):
  File "Tutorial.py", line 89, in <module>
    Result = test.Imputing(Methods)
  File "/xxxxx/xxxxx/SpatialBenchmarking/Benchmarking/SpatialGenes.py", line 296, in Imputing
    result_Novosparc = self.novoSpaRc_impute()
  File "/xxxxx/xxxx/SpatialBenchmarking/Benchmarking/SpatialGenes.py", line 190, in novoSpaRc_impute
    np.save(novo.npy, gw)
NameError: name 'novo' is not defined

**Comment by vinsilico** [comment]
fixed the issue by single quoting the novo.npy.
